### ISSUE TITLE
Feature idea: allow for multiple specs

### ISSUE THREAD

**Issue by mcdonc** [Pylons/pyramid_openapi3#11]
I see that the openapi validator is currently implemented as a view deriver, which is perfectly reasonable.  In a more complex world, it might (I dunno, maybe not) be useful to be able to say:

```
@view_config(route_name='whatever', renderer='path/to:whatever.openapi')
def whatever(request):
    # do the needful
    pass
```

... where whatever.openapi was the actual spec file, allowing for more than one spec to be used in the app at a time.  It's just a thought.

**Comment by zupo** [comment]
Closing due to lack of interest. I'll gladly reopen if someone who wants/needs this steps up.
