### ISSUE TITLE
Open up explorer to non logged in users.

### ISSUE THREAD

**Issue by afreepenguin** [Pylons/pyramid_openapi3#119]
Is there a way to open up the explorer view so that NO_PERMISSION_REQUIRED can be applied. Saw something in the changelog that seemed to indicate it's possible but wasn't able to find any documentation.

**Comment by afreepenguin** [comment]
> https://github.com/niteoweb/pyramid-realworld-example-app/, that is deployed on https://pyramid-openapi3.pylonsproject.org/ has the explorer available to unauthenticated users on https://pyramid-openapi3.pylonsproject.org/api.
> 
> Is this what you need? If yes, then looking at https://github.com/niteoweb/pyramid-realworld-example-app/ should help.

Can't seem to get it working when using AuthTktAuthenticationPolicy. The only way I can see to get around it is by modifying unauthenticated_userid function within AuthTktAuthenticationPolicy and checking to see if the path being requested matches the API explorer then setting some temporary authenticated user. Would be nice if I could pass NO_PERMISSION_REQUIRED to the pyramid_openapi3_add_explorer setup.

**Comment by zupo** [comment]
Ah OK, that explains it, as I usually use https://github.com/wichert/pyramid_jwt for authentication on pyramid apps that provide a REST API. 

Could you create a PR that add this? Along with a test.

**Comment by afreepenguin** [comment]
> Ah OK, that explains it, as I usually use https://github.com/wichert/pyramid_jwt for authentication on pyramid apps that provide a REST API.
> 
> Could you create a PR that add this? Along with a test.

Started looking into the code and realized the latest version here actually addresses this, I was on an older version. Appears to be working as expected, I will close this. Thanks.
