### ISSUE TITLE
Race condition with the validator base_urls

### ISSUE THREAD

**Issue by sevanteri** [Pylons/pyramid_openapi3#126]
Commit 4e485f1dc2eb1a74488e86faf46c20b6141676cf adds `request.application_url` into the **global** `settings` on every request. This causes a race condition with concurrent requests flooding in.

**Comment by zupo** [comment]
Hmm, I see, good find, thanks for the report.

Do you possibly have any time to work on a fix?

**Comment by sevanteri** [comment]
I'm wondering if the relative servers are actually now handled correctly in openapi-core.
https://github.com/p1c2u/openapi-core/blob/master/openapi_core/templating/paths/finders.py#L78-L80

**Comment by zupo** [comment]
Fixed in https://github.com/Pylons/pyramid_openapi3/pull/127.
