### ISSUE TITLE
No module named 'openapi_core.schema.exceptions'

### ISSUE THREAD

**Issue by BoomerB** [Pylons/pyramid_openapi3#129]
File "/usr/local/lib/python3.8/site-packages/pyramid/config/__init__.py", line 632, in include
    c = self.maybe_dotted(callable)
  File "/usr/local/lib/python3.8/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
    return self.name_resolver.maybe_resolve(dotted)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 327, in maybe_resolve
    return self._resolve(dotted, package)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 334, in _resolve
    return self._zope_dottedname_style(dotted, package)
  File "/usr/local/lib/python3.8/site-packages/pyramid/path.py", line 383, in _zope_dottedname_style
    found = __import__(used)
  File "/usr/local/lib/python3.8/site-packages/pyramid_openapi3/__init__.py", line 3, in <module>
    from .exceptions import extract_errors
  File "/usr/local/lib/python3.8/site-packages/pyramid_openapi3/exceptions.py", line 3, in <module>
    from openapi_core.schema.exceptions import OpenAPIError
ModuleNotFoundError: No module named 'openapi_core.schema.exceptions'

> python3.8 -m pip  list | grep -E 'pyramid|openapi'
openapi-core             0.14.0
openapi-schema-validator 0.1.5
openapi-spec-validator   0.3.0
pyramid                  2.0
pyramid-openapi3         0.11

**Comment by BoomerB** [comment]
quick fix

/usr/local/lib/python3.8/site-packages/pyramid_openapi3> diff -u exceptions.py-orig exceptions.py
--- exceptions.py-orig  2021-05-08 11:36:52.303272870 +0200
+++ exceptions.py       2021-05-08 12:03:14.760813652 +0200
@@ -1,6 +1,6 @@
 """Exceptions used in pyramid_openapi3."""

-from openapi_core.schema.exceptions import OpenAPIError
+from openapi_core.exceptions import OpenAPIError
 from openapi_core.unmarshalling.schemas.exceptions import InvalidSchemaFormatValue
 from pyramid.httpexceptions import HTTPBadRequest
 from pyramid.httpexceptions import HTTPInternalServerError

**Comment by damonhook** [comment]
The `exceptions` were moved as part of the 0.14.0 release of openapi-core (see [release](https://github.com/p1c2u/openapi-core/releases/tag/0.14.0)).

Currently pyramid_openapi3 supports openapi-core 0.13.7 (see [Pipfile.lock](https://github.com/Pylons/pyramid_openapi3/blob/master/Pipfile.lock#L93) and [Readme](https://github.com/Pylons/pyramid_openapi3#deprecation-policy))

---

Looks like a some work will need to be done to support 0.14.0

**Comment by garyburgmann** [comment]
`setup.py` does not pin the minor version:

```python
install_requires=["openapi-core>=0.13.4", "openapi-spec-validator", "pyramid"],
```

just explicitly add the package to your `requirements.txt` (or similar) as `openapi-core>=0.13.4,<0.14`

**Comment by zupo** [comment]
Fixed in https://pypi.org/project/pyramid-openapi3/0.12/.
