### ISSUE TITLE
Possible to have multiple versions? 

### ISSUE THREAD

**Issue by andrewfree** [Pylons/pyramid_openapi3#130]
Looking at this line, is it possible for an app to have multiple API versions? I've been able to manage multiple versions of an endpoint using path variables like /api/v{version} but not sure if the API from pyramid_openapi perspective can have multiple versions listed in the explorer in some way?

`config.pyramid_openapi3_spec_directory('path/to/openapi.yaml', route='/api/v1/spec')`

Thanks

**Comment by zupo** [comment]
Have you found a solution for this?
