### ISSUE TITLE
Broken tests in master

### ISSUE THREAD

**Issue by zupo** [Pylons/pyramid_openapi3#136]
Sometimes, `make unit` tests are run in a certain order that make three of them fail. To reproduce this particular order locally, run this: `make unit args="--randomly-seed=12988384"`.

The above command fails locally for me on Python 3.8 and Python 3.9. Same on CI.

The culprit seems to be moving validation to an earlier point in https://github.com/Pylons/pyramid_openapi3/commit/84b459ffa44f453e83022553759043355b9b24e3. 

@gjo: since you are the author of the above commit, could you please take a look if you can figure out what's wrong with the tests?

**Comment by zupo** [comment]
Also see https://github.com/Pylons/pyramid_openapi3/pull/132#issuecomment-843080062

**Comment by gjo** [comment]
I think that the global variable `pyramid_openapi3.APIS` has a bad side effect in multiple instantiation environments like testing.

https://github.com/gjo/pyramid_openapi3/commit/ead104daa847e09e7a1e013c62e90ec007516166

**Comment by gjo** [comment]
This variable has been introduced on https://github.com/Pylons/pyramid_openapi3/commit/65351ea86356e5214f02fb28d17b2ade0ba628a2

**Comment by zupo** [comment]
@sweh: ^^

**Comment by zupo** [comment]
@gjo: the changes in your branch look good to me, care to make a PR?

**Comment by sweh** [comment]
I'm not a big fan of that global variable. Any idea how we can improve this?

**Comment by gjo** [comment]
I will try to finish it in next weekend.
