### ISSUE TITLE
Problem with openapi-core dependency

### ISSUE THREAD

**Issue by daryllstrauss** [Pylons/pyramid_openapi3#137]
When I pip install pyramid-openapi3, openapi-core version 0.14.2 gets installed. The version causes an error with finding exceptions.

- docker run --rm -it fedora:34 bash
- pip install pyramid-openapi3
- pip freeze | grep openapi

openapi-core==0.14.2
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.1
pyramid-openapi3==0.11

The setup.py requires 'openapi>=0.13.4,<0.14'. I then explicitly included that in my project's setup.py, and that install openapi-core==0.13.8 and works properly.

Is the version in pypi out of sync?

**Comment by stevepiercy** [comment]
Yes. 0.11 is the latest release on 2021-02-15.
https://pypi.org/project/pyramid-openapi3/#history

This PR merged on 2021-05-16 has not been released to PyPI.
https://github.com/Pylons/pyramid_openapi3/pull/131/files

**Comment by zupo** [comment]
What @stevepiercy said. I'm waiting for https://github.com/Pylons/pyramid_openapi3/issues/136 to get resolved before I cut a new release.
