### ISSUE TITLE
Validation for different API versions.

### ISSUE THREAD

**Issue by afreepenguin** [Pylons/pyramid_openapi3#140]
I noticed you can have multiple API explorers for different versions. However, it isn't clear to me how I can still use  openapi=True in the view config and pick what version it validates against?
   
```
  config.pyramid_openapi3_spec(
        "openapi.yaml", route="/api/v1/openapi.yaml", route_name="pyramid_openapi3.spec"
    )
    config.pyramid_openapi3_spec(
        "openapi2.yaml",
        route="/api/v2/openapi.yaml",
        route_name="pyramid_openapi3.spec2",
        apiname="pyramid_openapi3_2",
    )

    config.pyramid_openapi3_add_explorer(
        route="/api/v1/", route_name="pyramid_openapi3.explorer",
    )
    config.pyramid_openapi3_add_explorer(
        route="/api/v2/",
        route_name="pyramid_openapi3.explorer_2",
        apiname="pyramid_openapi3_2",
    )
```

**Comment by zupo** [comment]
I don't think we have first-class support for multiple API versions, sorry.

**Comment by zupo** [comment]
I was mistaken, we do: https://github.com/Pylons/pyramid_openapi3/pull/111

Maybe @sweh can help answer this.

**Comment by zupo** [comment]
Based on this test: https://github.com/Pylons/pyramid_openapi3/pull/111/files#diff-224b7fa902e17800662b5478127e7a0778220756db05cb64db263b48260cf280R387

It seems the route dictates what openapi.yaml is used for validation. Which makes a ton of sense! 

@afreepenguin: I hope this answer your questions. If not, please let me know.
