### ISSUE TITLE
Links feature

### ISSUE THREAD

**Issue by karolpawlowski** [Pylons/pyramid_openapi3#144]
Hey Guys,

OpenAPI has something like `links` https://swagger.io/docs/specification/links/

But for me they don't seem to be generated properly:
![Screenshot 2021-06-24 at 15 05 01](https://user-images.githubusercontent.com/2912430/123267670-8ea62680-d4fd-11eb-8e35-83386af8d604.png)
![Screenshot 2021-06-24 at 15 05 43](https://user-images.githubusercontent.com/2912430/123267785-ad0c2200-d4fd-11eb-985e-5bc951dcbbb3.png)

1. Is this OpenAPI issue or this library has to support this?
2. Where I can find those links in response body/headers? Should they be automatically added to successful response or I should add them manually in the view response? (if so, how?)

Thanks in advance!

**Comment by zupo** [comment]
Hey @karolpawlowski!

This package does not do any generation, it only verifies requests & responses. So you'll have to add the links to responses yourself, in your code.

**Comment by karolpawlowski** [comment]
Thanks @zupo !
