### ISSUE TITLE
Allow registering multiple apis in a single pyramid app when the spec is directory

### ISSUE THREAD

**Issue by potkae** [Pylons/pyramid_openapi3#145]
Pull request #111 implemented registering multiple apis in a single pyramid app when the spec is a single file. However it did not take into account having the same functionalities in `pyramid_openapi3_spec_directory`. It would be consistent to support the same functionalities for spec directories as well.

**Comment by zupo** [comment]
@sweh: do you have any free time during summer to work on this? No rush.

**Comment by sweh** [comment]
@zupo: Assign it to me, I'll look into this in the coming days.

**Comment by potkae** [comment]
Any news on this? Have you had time to take a look?

**Comment by damonhook** [comment]
I have a PR fo issue #149 that should handle this issue as well
