### ISSUE TITLE
Swagger UI: array after deleting all elements remains in the request

### ISSUE THREAD

**Issue by karolpawlowski** [Pylons/pyramid_openapi3#148]
1. I have an array[integer] parameter. 
2. When I don't set any values it doesn't appear in the request.

![Screenshot 2021-08-02 at 15 32 09](https://user-images.githubusercontent.com/2912430/127870492-f6b3c00a-fa8d-4548-bc2e-5e8829f612b9.png)
![Screenshot 2021-08-02 at 15 34 05](https://user-images.githubusercontent.com/2912430/127870579-0df4677f-d921-42ea-8979-fe2655af54d3.png)

3. When I added a param, value properly appears in the request

![Screenshot 2021-08-02 at 15 31 35](https://user-images.githubusercontent.com/2912430/127870687-a4323956-286f-43c8-9072-2397b1cb815f.png)
![Screenshot 2021-08-02 at 15 31 30](https://user-images.githubusercontent.com/2912430/127870697-5c45556f-2802-4723-ab81-68847a5b6679.png)

4. When I delete the value and execute again, empty param remains in the request. 
![Screenshot 2021-08-02 at 15 32 43](https://user-images.githubusercontent.com/2912430/127870855-f2a59d19-1068-4f20-98a8-2fa1c1c40da7.png)

Expected behaviour: array type param shouldn't be passed to a request if there are no values anymore.

What do you think? Is it this library bug or I should report this somewhere else?

**Comment by zupo** [comment]
This looks like a bug with Swagger UI and not with pyramid_openapi. Please report at https://github.com/swagger-api/swagger-ui.
