### ISSUE TITLE
Swagger UI (Explorer) is attempting to run external validation (fails when spec file is not public)

### ISSUE THREAD

**Issue by damonhook** [Pylons/pyramid_openapi3#152]
By default Swagger UI will attempt to run its own validation on the spec. However, since this validation runs externally and not in your pyramid service, if your OpenApi spec is not publicly accessible then it will fail their validation.

On the version of Swagger UI that we are currently using (3.17.1), you may not notice the failure (since the "invalid" badge does not show), however, you can see the requests being made (validation fails due to the spec file being unreachable externally)

Here is an example using one of the `example` apps
![ui-validator-current](https://user-images.githubusercontent.com/35456894/129891854-934608d9-a484-40a1-a64c-52bda319e98b.png)

However, on newer versions of Swagger UI, this invalid badge starts to appear
![ui-validator-future](https://user-images.githubusercontent.com/35456894/129891902-aabf316f-8d1f-467b-8553-2db0658385ff.png)

---

Since we already have spec validation being done by the pyramid service itself, is there any objection to disabling this external validation (I can create a quick PR to do so).

This can be done by setting `validatorUrl` to `null` in the `SwaggerUIBundle`

**Comment by zupo** [comment]
+1 for disabling
