### ISSUE TITLE
`renderer="json"` for exception view looks needless

### ISSUE THREAD

**Issue by atronah** [Pylons/pyramid_openapi3#154]
I don't understand what is the purpose of using `renderer="json"` argument in [that code](
https://github.com/Pylons/pyramid_openapi3/blob/54b5c785669574787a55e7717ba4d1885c3653ce/pyramid_openapi3/__init__.py#L59):

```python
config.add_exception_view(
        view=openapi_validation_error, context=RequestValidationError, renderer="json"
    )

    config.add_exception_view(
        view=openapi_validation_error, context=ResponseValidationError, renderer="json"
    )
```

`openapi_validation_error` returns `Response` object and if I understand correctly, in that case renderers are [avoided by Pyramid handlers](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/renderers.html), aren't?

Or I'm missing something?

**Comment by zupo** [comment]
From the top of my head: no idea. 

Did you try removing the `rendered="json"` and seeing what happens?

**Comment by zupo** [comment]
Closed with https://github.com/Pylons/pyramid_openapi3/pull/171, thanks for reporting @atronah!
