### ISSUE TITLE
WooCart example link down

### ISSUE THREAD

**Issue by miohtama** [Pylons/pyramid_openapi3#156]
The example link in README does not work

<img width="1732" alt="image" src="https://user-images.githubusercontent.com/49922/134493043-894647fa-3463-4910-8230-fcef34611bb0.png">

**Comment by zupo** [comment]
Thanks!

Fixed in https://github.com/Pylons/pyramid_openapi3/commit/51fc7fa0d4265bf477d3de06c2c76a3bfafafe64.
