### ISSUE TITLE
__init__() got an unexpected keyword argument 'resolver' in openapi_spec_validator/validators.py when calling pyramid_openapi3_spec

### ISSUE THREAD

**Issue by karolpawlowski** [Pylons/pyramid_openapi3#160]
Hey, I'm trying to build and run my project on M1 device. I'm using docker linux/amd64 image by specifying `FROM --platform=linux/amd64 python:3.8.5-slim` in docker file and everything builds just fine.

But when running the project (with `docker-compose up`), I've got this error:

```
File "/usr/local/lib/python3.8/site-packages/openapi_spec_validator/validators.py", line 342, in iter_errors
validator = OAS30Validator(
pyramid.exceptions.ConfigurationExecutionError: <class 'TypeError'>: __init__() got an unexpected keyword argument 'resolver'
in:
Line 22 of file <path>/utils.py:
     config.pyramid_openapi3_spec(
        os.path.join(os.path.dirname(__file__), "openapi.yaml"),
        route="/api/v1/openapi.yaml",
    )
```

I have `pyramid-openapi3==0.13` in my requirements.txt

Any ideas what could be wrong? It was working on intel based machine before.

Just to mention:
1. project builds and runs on intelbase machine without specifying `--platform=linux/amd64` in Dockerfile.
2. project builds and runs on intelbase machine with specified `--platform=linux/amd64` in Dockerfile too...

UPDATE: problem was fixed after upgrading pip by running `pip install --upgrade pip` before installing requirements.
Image based pip version: 20.2.3
Upgraded pip version: 21.3.1 
But I'm leaving this ticket open for your consideration. Maybe there is a problem with dependencies?

**Comment by zupo** [comment]
To me, this seems like an environment problem, i.e. you had to upgrade your system-wide pip. I'm gonna close this in a few days if noone else reports it.
