### ISSUE TITLE
Anounce stable release

### ISSUE THREAD

**Issue by zupo** [Pylons/pyramid_openapi3#18]
- [x] Announcement blog post: https://blog.niteo.co/robust-rest-apis-with-pyramid/
- [x] Announce to https://groups.google.com/forum/#!forum/pylons-discuss.
- [x] Announce via Twitter https://twitter.com/pylonsproject.
- [x] Outreach:
  - [x] https://www.reddit.com/r/webdev
  - [x] https://www.reddit.com/r/Python/
  - [x] https://news.ycombinator.com
  - [x] https://lobste.rs/

**Comment by stevepiercy** [comment]
@zupo do you have a draft announcement anywhere, or at least the history or good story, including why move this under the Pylons Project?

Is the blog NiteoWeb's or your personal one?

I can do the Twitter post or grant you access to tweet on behalf of pylonsproject via TweetDeck.

**Comment by zupo** [comment]
> @zupo do you have a draft announcement anywhere, or at least the history or good story, including why move this under the Pylons Project?

No, not yet. I want to do a 1.0 release first and run it in production for a few days.

> Is the blog NiteoWeb's or your personal one?

I was planning to post to https://blog.niteo.co/, but I'm completely fine posting somewhere else.

> I can do the Twitter post or grant you access to tweet on behalf of pylonsproject via TweetDeck.

I'm fine with you doing posting, just wait till I get the 1.0 out there.

**Comment by stevepiercy** [comment]
We don't have a blog, so yours is good. I can derive content from that post for posting on Twitter, and refer to it.

**Comment by zupo** [comment]
All done.
