### ISSUE TITLE
Help with setting up 

### ISSUE THREAD

**Issue by kskarthik** [Pylons/pyramid_openapi3#185]
Hello. I am trying to setup the latest version of this plugin for pyramid v2 application gkcore (https://gitlab.com/gnukhata/gkcore/) , I faced an issue with getting started section. I have added the config & tried to launch the app & i get this following err. 

Please help me out, Thank you

![image](https://user-images.githubusercontent.com/11899221/204205459-a749cd6c-5e13-4873-9435-68112a6f9d2a.png)

**Comment by kskarthik** [comment]
The error seems to come from https://github.com/p1c2u/openapi-spec-validator

**Comment by zupo** [comment]
We don't (yet) support the most recent version of openapi-core and openapi-spec-validator.

Here is a list of versions that are tested to work. Start from here, then update to later versions one by one, as you need to: https://github.com/Pylons/pyramid_openapi3/blob/main/poetry.lock#L1192

**Comment by kskarthik** [comment]
@zupo thank you for the link, pinning `openapi-spec-validator == 0.4` works for now!

**Comment by zupo** [comment]
No, not intended. We should list the highest supported version. It's on my TODO, but my open source time was very limited in recent months, so I haven't gotten around to it yet. Will gladly accept a PR if you want to do it!

**Comment by kskarthik** [comment]
@zupo i have encountered a small issue, the api spec can't load the yaml at https://api.gnukhata.org/docs/ due to mixed content issue, Did i miss anything? Please help

Config https://gitlab.com/gnukhata/gkcore/-/blob/devel/gkcore/__init__.py#L109

**Comment by zupo** [comment]
What parameters do you want to tweak?

This is the view: https://github.com/Pylons/pyramid_openapi3/blob/c281e1f3ad518d05322558e1f4b8cf7ed966f729/pyramid_openapi3/__init__.py#L142

Here the URL is passed into the index.html template: https://github.com/Pylons/pyramid_openapi3/blob/c281e1f3ad518d05322558e1f4b8cf7ed966f729/pyramid_openapi3/__init__.py#L174

**Comment by kskarthik** [comment]
@zupo i meant, the swagger UI should load the spec file from the https endpoint instead of http. So, asked if there is a way to do so

**Comment by kskarthik** [comment]
Well, For now, i solved the issue by self hosting swagger ui at https://gnukhata.org/api/ 

I feel the the swagger ui locally is a bit outdated, is it?

**Comment by zupo** [comment]
> @zupo i meant, the swagger UI should load the spec file from the https endpoint instead of http. So, asked if there is a way to do so

It should do this, yes. If it doesn't, we have a bug. Can you provide a minimal example that showcases the bug?

**Comment by zupo** [comment]
> I feel the the swagger ui locally is a bit outdated, is it?

You can override it: https://github.com/Pylons/pyramid_openapi3/blob/main/pyramid_openapi3/__init__.py#L147

**Comment by kskarthik** [comment]
> It should do this, yes. If it doesn't, we have a bug. Can you provide a minimal example that showcases the bug?

Yes https://api.gnukhata.org/docs/

**Comment by zupo** [comment]
The linked files include a bunch of code that is probably not needed to reproduce the bug. Please remove everything but the bare minimum to reproduce the bug. Put it into a completely separate repo, if that is easier. Or in a test case and push it into a fork of this repo.
