### ISSUE TITLE
OpenAPI 3.1 Support

### ISSUE THREAD

**Issue by damonhook** [Pylons/pyramid_openapi3#196]
## Summary

OpenAPI version 3.1 is out and supported by [openapi-core](https://github.com/p1c2u/openapi-core). Can we add support for it in this library as well?

## Requirements

Unfortunately 3.1 is not yet supported by Swagger UI (ref: https://github.com/swagger-api/swagger-ui/issues/5891). Once support has been added to Swagger UI, we could add it to this library as well.

## Implementation

> **Note**
> Once Swagger UI has 3.1 support

In order to use 3.1, the following code can be changed to use `OAS31Validator`. 
https://github.com/Pylons/pyramid_openapi3/blob/368119d926ebf5a84d78a061664fbf673c57c119/pyramid_openapi3/__init__.py#L314-L323

### Backwards Compatibility

If we want to keep backwards compatibility with 3.0 specs, we could look at the `openapi` version present in the spec itself, and swap out the validator accordingly.

**Comment by zjhamm** [comment]
It looks like 3.1 is now supported. Can we get this work started?

**Comment by zupo** [comment]
@zjhamm: happy to review PRs that bring us closer to OpenAPI v3.1!

**Comment by miketheman** [comment]
I was poking at this, and found what might be an issue. I started the conversation here: https://github.com/python-openapi/openapi-core/discussions/810
