### ISSUE TITLE
Help me configure the endpoint to serve the openapi.yaml

### ISSUE THREAD

**Issue by jschaeff** [Pylons/pyramid_openapi3#200]
Hello,

first thank you for this very usefull library.
 I'm deploying a pyramid project using this library. The code works fine in a docker deployment serving the `/` endpoint.

But in the production deployment, there is a prefix to set, and I could not find the right settings for this.

I tried to set the prefix in several ways, the more consistent to me was to add `route=` in the `pyramind_openapi3_spec()` function like this:

        config.pyramid_openapi3_spec(os.path.join(os.path.dirname(__file__), "openapi.yaml"), route='eidaws/statistics/1/openapi.yaml')

But it did not work. 

Can you tell me how to configure correctly the endpoint prefix ? (and maybe add this usecase in the documentation, as it seems not that exotic to me :)  )

Cheers,

**Comment by zupo** [comment]
I don't understand what you are trying to achieve. Can you please provide a runnable example? 

Some random thoughts:
* Have you set the `url` in your `openapi.yaml`? https://swagger.io/docs/specification/api-host-and-base-path/
* Here's a PR that seems to be related to prefixes: https://github.com/Pylons/pyramid_openapi3/pull/147/files

**Comment by jschaeff** [comment]
Thank you for the hints, it's not doing what we are looking for.

A workable exemple, is for instance the image : 

    docker pull ghcr.io/eida/eida-statistics:dev_pyramid

It serves the methods of the webservices on '/' and everything is working fine.

When this container is deployed in production, a reverse proxy maps the requests "eidaws/statistics/1/" to this webservice. In this configuration, the swagger UI says that "/openapi.yaml" is not available. As a matter of fact, it's served at "eidaws/statistics/1/openapi.yaml"

**Comment by zupo** [comment]
FWIW, I run Docker in production, and what you describe works fine. I don't see anything obvious besides, a potential bug in the `openapi.yaml` definition.

**Comment by jschaeff** [comment]
Thank you again for your help.
At the end, I managed to make my application prefix-aware by
- providing a prefix as environment variable
- editing dynamically the openapi.yaml file to change the paths in order to add this prefix
- giving this modified openapi.yaml file and setting the route option  
- adding the prefix on all route declarations

See https://github.com/EIDA/eida-statistics/blob/be0c120d73f479929fad2253b2dcce96ea61fc26/webservice/ws_eidastats/__init__.py

It seems a bit cumbersome, but I managed to keep everything consistent this way.

**Comment by zupo** [comment]
Great to hear you got it working! Thanks for writing in with a workaround that you used! I'm sure it will be useful to others in the future!
