### ISSUE TITLE
Can't access the swagger UI locally on Windows

### ISSUE THREAD

**Issue by Ankita-dev-hue** [Pylons/pyramid_openapi3#209]
http://localhost:6543/docs
http://0.0.0.0:6543/docs/

I tried accessing the swagger UI with the above 2 URLs on Win11 with the application running. Can you please help me with this?

<img width="879" alt="image" src="https://github.com/Pylons/pyramid_openapi3/assets/78083022/2a53c2a3-3a1e-4f2b-a2ee-4b6bac6833a4">
<img width="286" alt="image" src="https://github.com/Pylons/pyramid_openapi3/assets/78083022/fdd245c5-3b12-40f1-90a7-c46b3f9bfac2">

**Comment by zupo** [comment]
I personally do not have access to a Windows machine, so can't help with this one.

**Comment by zupo** [comment]
https://github.com/Pylons/pyramid_openapi3/blob/main/examples/singlefile/app.py#L67

**Comment by kskarthik** [comment]
Oh, I somewhere read that windows does not allow user to access the 0.0.0.0 ip

**Comment by kskarthik** [comment]
This issue is solved! It was config related
