### ISSUE TITLE
Update to supported versions?

### ISSUE THREAD

**Issue by miketheman** [Pylons/pyramid_openapi3#219]
Hello! Thanks for making this plugin.
I was trying it out in an attempt to adopt OpenAPI specifications (and request validation, and the other features this provides) to an existing codebase, which is tricky, for sure!

I hit the issue reported in #203 and pinned to openapi-core 0.16.x to get things generally working.

I also read through the upgrade efforts set in #206 and wanted to understand if it's a 100% foregone conclusion that this library intends to update to OpenAPI 3.1.x, or would it be acceptable to attempt to update the code to the latest openapi-core 0.19.0 and preserve OpenAPI 3.0.0 semantics as a stepping stone?
I'm definitely 👍 on moving towards 3.1.0, but would that be too much change?

Another version support question: Pyramid 2.0 was released in early 2021 - should newer versions of this library still attempt to maintain backwards compatibility, or would it be desirable to update the code and tests to assume at least 2.x ?

**Comment by zupo** [comment]
Hey @miketheman! 

So far, everyone that worked on #206 expressed they would want to upgrade to OpenAPI 3.1, so the code was written as such. I am not against adding changes to it for backwards compatibility with Open API 3.0, but I don't have the bandwidth to do is, so someone else will have to contribute these changes. 

About dropping Pyramid <2.0 support, I'm happy to review a PR that does it too.

**Comment by miketheman** [comment]
Excellent! I started https://github.com/Pylons/pyramid_openapi3/pull/220 so far

**Comment by miketheman** [comment]
Now that the "heavy" work was done, I'll proceed with an update to support Pyramid 2.0 and above.

Re: OpenAPI 3.0 - I'm now thinking that since there's already breaking changes in the underlying libraries, this _would_ be a good time to go for 3.1.0 - so that anyone upgrading to the latest library should also be encouraged to upgrade to the latest specification.

How does that sound?

**Comment by zupo** [comment]
I'll cut a release with 3.0 support before we merge 3.1, just so that people that need to stay on 3.0 can get the latest fixes in openapi-core. 

Other than that, please continue!

**Comment by zupo** [comment]
@miketheman: heads-up: I'm already working on adding python 3.12 support in https://github.com/Pylons/pyramid_openapi3/pull/224

**Comment by zupo** [comment]
@miketheman: also, please post PRs directly to this repo, so it's easier for me to help out on them -- I just sent you an invite to get permissions!

**Comment by miketheman** [comment]
Listing some version updates done:

- openapi-core 0.19 support added #220
- Python 3.12 support added #224
- OAS3.1 support added #230

I'm thinking that it doesn't "cost" anything to keep the Pyramid 1.x support around, other than some deprecation warnings during the test suite. If Pyramid ever starts to error for those, then we can update the sample apps as a result.

I think that is enough to close this out for now.
