### ISSUE TITLE
Path parameter validation fails.

### ISSUE THREAD

**Issue by gweis** [Pylons/pyramid_openapi3#25]
I am not sure whether this is an issue in openapi-core or whether this pkg needs to look at parameter validation differently, but I thought I'll start the conversation here.

OpenAPI 3 allows for parameter definition directly on a [Path Item object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#path-item-object). These parameters should be applicable to all operations under this path. However, the way validation works here is that only parameters defined on an 'Operation object' are considered for validation. If my understanding of the spec is correct, then either `pyramid_openapi3` should check whether there are `Path Item Object` parameters available and use them during validation, or `openapi-core` would need to expose these path parameters on the operation object.

I have put a test together to demonstrate the issue https://github.com/gweis/pyramid_openapi3/commit/b9bfd30c6d19c0a0d51122ccae044cca3575a5c5.

**Comment by zupo** [comment]
Massive 🙏 for whipping up a test to demonstrate the bug!

This looks like a bug in `openapi-core` and should be reported there. Ideally, the `openapi-core` deals with all validation, so there is a single source-of-truth of where validation happens.

**Comment by gweis** [comment]
@zupo Has been fixed and released (openapi-core 0.11.0) upstream (at least as far as my use case is concerned).

When updating `openapi-core` #24 should fix potential other issues with parameter validation as well.

**Comment by zupo** [comment]
Great, thanks, I'll have a look!

**Comment by zupo** [comment]
Yep, I also confirm that upgrading openapi-core from `0.10.0` to `0.11.0` makes the given test case pass on my local. I presume this can be closed. Please reopen if I am mistaken.
