### ISSUE TITLE
simplify this

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_openapi3#35]
https://github.com/Pylons/pyramid_openapi3/blob/5d77dcb171ce7e611bebd4fb76408dca74d236b3/pyramid_openapi3/tween.py#L45-L52

This could simply be `return request.invoke_exception_view(reraise=True)` as it internally can deal with the exc_info stuff itself. A small improvement if someone wanted to do it.

**Comment by gweis** [comment]
The difference is, that `request.invoke_exception_view` will always reraise an exception, but this code here only re-raises the original exception if there is no exception view registered (or can't be found).

i.e. it is not hiding other errors that may happen inside an `exception_view`.
