### ISSUE TITLE
setup.py install_requires needs constraints too

### ISSUE THREAD

**Issue by ztane** [Pylons/pyramid_openapi3#74]
Pipenv does not give constraints for packages in PyPI. The install_requires must have constraints for the package versions for pip and pip-compile to find the working versions for openapi core et al.

**Comment by zupo** [comment]
Hey ztane! We've had constraints for `openapi-core` in setup.py in the past when `pyramid_openapi3` was absolutely broken with latest `openapi-core`. When we updated it, we removed the constraint. 

What bug are you hitting that would require constraints?

**Comment by bertjwregeer** [comment]
Pylons projects in general only pin the lowest version they support, by doing a `>=` constraint. We do not set upper constraints on any packages on purpose.

**Comment by ztane** [comment]
@zupo an employee had updated pyramid_openapi3 but there was no minimum for `openapi-core` so it hadn't been updated at all and was no longer compatible, and then when you take the *highest* version and it does not work either, then one needs to do quite a lot needless bisecting...

**Comment by zupo** [comment]
@ztane what bug are they hitting? I have a (smaller) project running latest `pyramid_openapi3` and `openapi-core` without problems, which would be impossible if `openapi-core` would be pinned to not-latest in `setup.py`.

**Comment by zupo** [comment]
Ah I just realized you are talking about minimum versions, not maximum versions! I'm +1 for adding minimum openapi-api version as a requirement in setup.py.
