### ISSUE TITLE
Mishandled validation for arrays

### ISSUE THREAD

**Issue by mkuczara** [Pylons/pyramid_openapi3#75]
Hello,

while validating array of objects, you're generating unhandled exceptions. The library is properly validating the fields however if the validation of a particular field in an object in an array fails, an exception occurs in line 122 of `/pyramid_openapi3/exceptions.py`, which assumes that all members of err.path are strings while in this particular case it can also be the integer (index array), which triggers

```
pyramid_openapi3/exceptions.py", line 122, in extract_errors
    field = "/".join(err.path)
TypeError: sequence item 1: expected str instance, int found
```

To reproduce it, it's enough to create a schema like:
```
openapi: 3.0.1
servers:
  - url: /
info:
  title: x
  version: 0.0.0
paths:
  /x:
    post:
      requestBody:
        description: k
        content:
          application/json:
            schema:
              required:
                - x
              type: object
              properties:
                x:
                  type: array
                  items:
                    $ref: "#/components/schemas/xx"
      responses:
        200:
          description: Successful request
        400:
          description: Wrong input
components:
  schemas:
    xx:
      required:
        - a
      type: object
      properties:
        a:
          type: number
```

and send a request

```
{
	"x":[
		{
			"a": "s"
		}]
}
```

**Comment by zupo** [comment]
Thanks! I'll try to take a look over the weekend. Nevertheless, Pull Requests welcome :)

**Comment by zupo** [comment]
@mkuczara: Hey, any chance you can try the [`list_validation`](https://github.com/Pylons/pyramid_openapi3/tree/fix/list_validation) branch on your openapi.yaml and report back if the proposed fix is good?

**Comment by zupo** [comment]
I've cut a bugfix release: https://pypi.org/project/pyramid-openapi3/0.8.1/
