### ISSUE TITLE
Upgrade SwaggerUI version to support examples

### ISSUE THREAD

**Issue by iustitia** [Pylons/pyramid_openapi3#77]
It looks like showing examples in responses and body is not supported currently. It was introduced in SwaggerUI in version 3.23.0, but pyramid_openapi3 supports only version 3.17.1.

Here is issue from SwaggerUI repo: https://github.com/swagger-api/swagger-ui/issues/2651

Any plans to upgrade to latest version of SwaggerUI?

**Comment by zupo** [comment]
The `add_explorer_view` allows you to pass `ui_version` to get an arbitrary version of Swagger UI. Have you tried this yet?

Additionally, I am not aware of any blockers that would prevent us from upgrading. Could you submit a PR that bumps the default [`ui_version`](https://github.com/Pylons/pyramid_openapi3/blob/fe9eda167b3e1f856f72c69af2fba8411a7b0ce7/pyramid_openapi3/__init__.py#L101) to a more recent one?

**Comment by iustitia** [comment]
Oh, I haven't noticed that, awesome :)
Maybe that could be mentioned on the Readme? I can do pull request for both.
