### ISSUE TITLE
pyramid_openapi3 incompatible with  openapi-core 0.13.4

### ISSUE THREAD

**Issue by sjiekak** [Pylons/pyramid_openapi3#87]
openapi-core introduced what I would consider a breaking change from 0.13.3 to 0.13.4. 
The commit https://github.com/p1c2u/openapi-core/commit/ac5c6762d83aea911fcc6c3bc775f432532a287d
which fixes https://github.com/p1c2u/openapi-core/issues/234

require to change how the request parameters are provided (see https://github.com/Pylons/pyramid_openapi3/blob/752299f56ec4e88f53d64b348b2ada231b3378ae/pyramid_openapi3/wrappers.py#L29)

``` 
parameters = RequestParameters(
    path=request.matchdict,
    query=request.GET,
    header=request.headers,
    cookie=request.cookies,
)
```

to 

``` 
parameters = RequestParameters(
    path=request.matchdict,
    query=request.GET,
    header=request.headers.items(),
    cookie=request.cookies,
)
```

**Comment by zupo** [comment]
Thanks for the nice bug report!

**Comment by zupo** [comment]
Superseded by https://github.com/Pylons/pyramid_openapi3/pull/89.

**Comment by sjiekak** [comment]
@zupo thanks
